pipeline:
  build:
    image: nexus.mytintern.com:5000/ci/base-php
    pull: true
    environment:
      - COMPOSER_HOME=.composer
    commands:
      - whoami
  publish:
    image: plugins/docker
    repo: nexus.mytintern.com:5000/gecco/shop
    tags: latest
